"""add my_card department/grade/job_function/address

Revision ID: 64ff2f7a2768
Revises: c41a7b9e2d08
Create Date: 2026-08-27 15:32:59.872932

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64ff2f7a2768'
down_revision: str | Sequence[str] | None = 'c41a7b9e2d08'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_card', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('my_card', sa.Column('grade', sa.String(length=100), nullable=True))
    op.add_column('my_card', sa.Column('job_function', sa.String(length=100), nullable=True))
    # EncryptedString always stores a Fernet token at String(500) regardless of the
    # declared length (see app/core/crypto.py) — matches how the phone/email columns
    # were widened in 55d6000b2f3d, and keeps this migration free of an app.core import.
    op.add_column('my_card', sa.Column('address', sa.String(length=500), nullable=True))
    op.drop_column('my_card', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_card', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('my_card', 'address')
    op.drop_column('my_card', 'job_function')
    op.drop_column('my_card', 'grade')
    op.drop_column('my_card', 'department')
    # ### end Alembic commands ###
