"""add person address_detail

Revision ID: acb826978ad1
Revises: cd0785d2b934
Create Date: 2026-08-28 16:20:52.490702

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.crypto import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "acb826978ad1"
down_revision: str | Sequence[str] | None = "cd0785d2b934"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("persons", sa.Column("address_detail", EncryptedString(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persons", "address_detail")
    # ### end Alembic commands ###
