"""add person image_path

Revision ID: b51b9ab07230
Revises: 64ff2f7a2768
Create Date: 2026-08-27 18:11:21.046582

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b51b9ab07230'
down_revision: str | Sequence[str] | None = '64ff2f7a2768'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'image_path')
    # ### end Alembic commands ###
