"""add person address and postal code

Revision ID: cd0785d2b934
Revises: 95380fa45b1d
Create Date: 2026-08-28 12:22:52.035719

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.crypto import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "cd0785d2b934"
down_revision: str | Sequence[str] | None = "95380fa45b1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("persons", sa.Column("address", EncryptedString(255), nullable=True))
    op.add_column("persons", sa.Column("postal_code", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persons", "postal_code")
    op.drop_column("persons", "address")
    # ### end Alembic commands ###
